### ISSUE TITLE
Downloader freeze after adding a single link and starting

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [shadoxxhd/steamworkshopdownloader#21] opened 2022-07-11 09:20 UTC
![image](https://user-images.githubusercontent.com/52252627/178231188-1c04de78-cc4f-4527-9dde-a5a923352d90.png)

For some reason, even when downloading only one mod, the window becomes unresponsive and nothing happens.
I have read the install guide, and logged into the SteamCMD, as this game requires my account to be connected.
I also own the game on Steam, so there should be no issues with getting these files.

Any help would be appreciated.

**Comment by shadoxxhd** [comment] 2022-07-11 18:51
Can you try to download something without being logged in (temporarily remove the login entry in the .ini file)? In the case of this game, that should print out an error, but not freeze.

**Comment by ykyoshi** [comment] 2022-07-15 11:10
Same issue here with a couple of GMod mods like this one: https://steamcommunity.com/sharedfiles/filedetails/?id=135509255
Downloading anonymously returns a timeout error.

**Comment by Lovecrafts-Cat** [comment] 2022-07-15 11:18
![image](https://user-images.githubusercontent.com/52252627/179212858-f0cabe14-5693-4225-82b9-9dd9a54fb1ee.png)
Sorry for the late reply. Downloading in anonymous mode returns an error, with no freeze.

Could this be caused by some login issue I'm not aware of?
I know that the 2FA code should work as long as I insert it the first time for login during the SteamCMD setup.
Could it be possible it doesn't somehow "remember" that it's logged in?

**Comment by shadoxxhd** [comment] 2022-07-15 11:39
That strongly suggests it is some kind of login issue, yes. Try starting steamcmd.exe manually, log in like in the README, but instead of typing `quit`, type `workshop_download_item 281990 2458928927` (or another valid appid/workshopID combination) and check if something freezes.

**Comment by shadoxxhd** [comment] 2022-07-15 11:41
And if the mod link was invalid, the program would simply tell you.

**Comment by shadoxxhd** [comment] 2022-07-22 10:38
For me, steamcmd seems to remember the 2fa authentication, but I'm using mail based 2FA instead of an offline key generator...

**Comment by shadoxxhd** [comment] 2022-07-28 18:56
One possible solution for this problem would be an option to open an interactive console in addition/instead of logging in the right text box, so the user could input their auth token if necessary.

Generating the codes from the master key seems to be out of scope for this project, and I'm not sure if there is a reliable way to detect steamcmd requiring additional input...

**Comment by Kussh** [comment] 2023-07-09 01:26
I have the same problem. I'm using anonymous login to download a Stellaris collection since I have the game on GOG, but it's listed for anonymous downloads thankfully. The downloader just freezes after showing me a couple of prompts and stays frozen.
I noticed somehow that steamcmd was still working in the background, so I tried again and just decided to leave the program do its thing, and yes, it's downloading and slowly populating the folder with the downloaded mods and doing its thing in the background. It finishes the downloads except for a single mod which is 3.2GB in size, sadly it even times out on steamcmd alone since my internet is not fast enough.

![Screenshot (5)](https://github.com/shadoxxhd/steamworkshopdownloader/assets/16672534/be49df5f-ba7f-4516-9f66-09abb3cb53b4)

**Comment by shadoxxhd** [comment] 2024-02-27 11:42
@Kussh this isn't the same problem. In your case, the download simply seems to be limited by your network speed - nothing anyone can do about that. Timeouts can sometimes be "fixed" simply by trying again, unless your internet is too slow/unreliable for a given file size.

**Comment by shadoxxhd** [comment] 2024-02-27 15:35
Better Steam Guard support was added in [v0.6.0](https://github.com/shadoxxhd/steamworkshopdownloader/releases/tag/v0.6.0).
That should solve these issues.

**Closed by shadoxxhd** 2024-02-27 15:35 UTC
Labels: bug, help wanted
