### ISSUE TITLE
Steamcmd opens and closes immediately

### ISSUE THREAD

**Issue by jumpthe11** [shadoxxhd/steamworkshopdownloader#35] opened 2022-08-24 17:45 UTC
just creates bootstrap_log.txt and writes 
`
[2022-08-24 20:39:12] Startup - updater built Dec  2 2013 18:43:44`

inside in it.

**Comment by jumpthe11** [comment] 2022-08-25 05:28
ok I found issue. downloader.exe MUST IN STEAM FOLDER

**Comment by jumpthe11** [comment] 2022-08-25 06:31
now downloader.exe wants 2 factor login even I did on steamcmd

**Comment by jumpthe11** [comment] 2022-08-25 07:07
![resim](https://user-images.githubusercontent.com/73638543/186598186-3e4e1b24-36b6-46e7-9de8-735fccc20824.png)

**Comment by shadoxxhd** [comment] 2022-11-20 18:07
This seems to be a duplicate of the issue behind #21.
Are you using app-based 2FA?

**Comment by jumpthe11** [comment] 2022-11-20 19:16
I guess yes. It has been long time since I used last time.

**Comment by shadoxxhd** [comment] 2023-02-05 23:13
Closing as duplicate of #21 .

**Closed by shadoxxhd** 2023-02-05 23:13 UTC
